import React, { useState, useEffect, useMemo } from 'react';
import { supabase } from '../services/supabase';
import { Session, EmailTemplate, CompanySettings, FormConfiguration } from '../types';
import { useTheme } from '../contexts/ThemeContext';
import { Modal } from './shared/Modal';
import { Tooltip } from './shared/Tooltip';

const createTableSql = `CREATE TABLE public.email_templates (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  uid uuid NOT NULL,
  template_name text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_uid_template_name_key UNIQUE (uid, template_name),
  CONSTRAINT email_templates_uid_fkey FOREIGN KEY (uid) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for users based on uid" ON public.email_templates FOR ALL USING (auth.uid() = uid) WITH CHECK (auth.uid() = uid);`;

const EDITABLE_TEMPLATES: Record<string, { name: string; description: string; placeholders: string[] }> = {
    customer_confirmation: {
        name: 'Customer Booking Confirmation',
        description: 'Sent to the customer when they submit a new booking via the public form.',
        placeholders: ['{{booking_id}}', '{{customer_name}}', '{{pickup}}', '{{dropoff}}', '{{datetime}}', '{{amount}}', '{{company_name}}']
    },
    admin_new_booking: {
        name: 'Admin New Booking Notification',
        description: 'Sent to the admin when a new booking is received from the public form.',
        placeholders: ['{{booking_id}}', '{{customer_name}}', '{{pickup}}', '{{dropoff}}', '{{datetime}}', '{{amount}}', '{{customer_contact}}']
    },
    driver_assignment: {
        name: 'Driver Ride Assignment',
        description: 'Sent to a driver when a new ride is assigned to them.',
        placeholders: ['{{driver_name}}', '{{booking_id}}', '{{pickup}}', '{{dropoff}}', '{{datetime}}', '{{customer_name}}', '{{company_name}}']
    },
    driver_cancellation: {
        name: 'Driver Ride Cancellation',
        description: 'Sent to a driver when their assigned ride is cancelled.',
        placeholders: ['{{driver_name}}', '{{booking_id}}', '{{pickup}}', '{{datetime}}', '{{company_name}}']
    },
    customer_cancellation: {
        name: 'Customer Booking Cancellation',
        description: 'Sent to the customer when their booking is cancelled by an admin.',
        placeholders: ['{{customer_name}}', '{{booking_id}}', '{{pickup}}', '{{company_name}}']
    },
    ride_completion: {
        name: 'Customer Ride Completion & Receipt',
        description: 'Sent to the customer with a receipt after their ride is marked as completed.',
        placeholders: ['{{customer_name}}', '{{booking_id}}', '{{pickup}}', '{{dropoff}}', '{{driver_name}}', '{{amount}}', '{{company_name}}']
    },
    driver_payment_notification: {
        name: 'Driver Payment Notification',
        description: 'Informs the driver about the payment method used for a completed ride.',
        placeholders: ['{{driver_name}}', '{{booking_id}}', '{{amount}}', '{{payment_mode}}', '{{company_name}}']
    }
};

const DEFAULT_TEMPLATES: Record<string, { subject: string; body: string; }> = {
    customer_confirmation: {
        subject: 'Your Booking is Confirmed! (Booking #{{booking_id}})',
        body: `<h2>Your Ride is Confirmed!</h2>
<p>Hi {{customer_name}},</p>
<p>Thank you for booking with {{company_name}}. Your ride details are below:</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Booking ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Pickup:</strong> {{pickup}}</li>
    <li style="margin-bottom: 10px;"><strong>Drop-off:</strong> {{dropoff}}</li>
    <li style="margin-bottom: 10px;"><strong>Time:</strong> {{datetime}}</li>
    <li style="margin-bottom: 10px;"><strong>Estimated Fare:</strong> \${{amount}}</li>
</ul>
<p>We will notify you when your driver is on the way. If you have any questions, feel free to contact us.</p>`
    },
    admin_new_booking: {
        subject: '[New Booking] Ride Request Received - #{{booking_id}}',
        body: `<h2>New Booking Notification</h2>
<p>A new booking has been submitted through your public form.</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Booking ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Customer:</strong> {{customer_name}}</li>
    <li style="margin-bottom: 10px;"><strong>Contact:</strong> {{customer_contact}}</li>
    <li style="margin-bottom: 10px;"><strong>Pickup:</strong> {{pickup}}</li>
    <li style="margin-bottom: 10px;"><strong>Drop-off:</strong> {{dropoff}}</li>
    <li style="margin-bottom: 10px;"><strong>Time:</strong> {{datetime}}</li>
    <li style="margin-bottom: 10px;"><strong>Estimated Fare:</strong> \${{amount}}</li>
</ul>
<p>Please log in to the admin panel to review the details and assign a driver.</p>`
    },
    driver_assignment: {
        subject: 'New Ride Assigned: Booking #{{booking_id}}',
        body: `<h2>New Ride Assignment</h2>
<p>Hi {{driver_name}},</p>
<p>A new ride from <strong>{{company_name}}</strong> has been assigned to you. Please log in to the driver portal for full details.</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Ride ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Customer:</strong> {{customer_name}}</li>
    <li style="margin-bottom: 10px;"><strong>Pickup Location:</strong> {{pickup}}</li>
    <li style="margin-bottom: 10px;"><strong>Pickup Time:</strong> {{datetime}}</li>
</ul>`
    },
    driver_cancellation: {
        subject: 'Ride Cancelled: Booking #{{booking_id}}',
        body: `<h2>Ride Cancelled</h2>
<p>Hi {{driver_name}},</p>
<p>The following ride assigned to you has been cancelled by the admin:</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Ride ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Original Pickup:</strong> {{pickup}}</li>
    <li style="margin-bottom: 10px;"><strong>Original Time:</strong> {{datetime}}</li>
</ul>
<p>This ride has been removed from your schedule. No action is needed from your side.</p>`
    },
    customer_cancellation: {
        subject: 'Your Booking Cancellation Confirmation (ID: #{{booking_id}})',
        body: `<h2>Booking Cancelled</h2>
<p>Hi {{customer_name}},</p>
<p>This email confirms that your booking with <strong>{{company_name}}</strong> has been successfully cancelled.</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Booking ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Pickup:</strong> {{pickup}}</li>
</ul>
<p>We're sorry to see you go. If this was a mistake or if you need to rebook, please visit our website or contact us directly. We hope to see you again soon.</p>`
    },
    ride_completion: {
        subject: 'Your Ride is Complete - Receipt for Booking #{{booking_id}}',
        body: `<h2>Thank You for Riding With Us!</h2>
<p>Hi {{customer_name}},</p>
<p>Your ride with <strong>{{company_name}}</strong> is complete. Here is a summary of your trip:</p>
<table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
    <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;">Booking ID:</td><td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">#{{booking_id}}</td></tr>
    <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;">From:</td><td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">{{pickup}}</td></tr>
    <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;">To:</td><td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">{{dropoff}}</td></tr>
    <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;">Driver:</td><td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">{{driver_name}}</td></tr>
    <tr style="font-weight: bold; font-size: 1.1em;"><td style="padding: 12px 8px 8px;">Total Charged:</td><td style="padding: 12px 8px 8px; text-align: right;">\${{amount}}</td></tr>
</table>
<p>We appreciate your business and hope you had a pleasant journey! We'd love to hear your feedback.</p>`
    },
    driver_payment_notification: {
        subject: 'Payment Information for Ride #{{booking_id}}',
        body: `<h2>Payment Information</h2>
<p>Hi {{driver_name}},</p>
<p>Please note the payment details for the completed ride:</p>
<ul style="list-style-type: none; padding: 0; margin-left: 0;">
    <li style="margin-bottom: 10px;"><strong>Ride ID:</strong> #{{booking_id}}</li>
    <li style="margin-bottom: 10px;"><strong>Fare:</strong> \${{amount}}</li>
    <li style="margin-bottom: 10px;"><strong>Payment Status:</strong> {{payment_mode}}</li>
</ul>
<p>This has been recorded in your payment history.</p>`
    }
};

const SetupInstructions: React.FC<{ sql: string }> = ({ sql }) => {
    const [copied, setCopied] = useState(false);
    const handleCopy = () => {
        navigator.clipboard.writeText(sql).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className="bg-amber-50 dark:bg-amber-900/20 p-6 rounded-lg border-l-4 border-amber-400 dark:border-amber-500">
            <div className="flex">
                <div className="flex-shrink-0">
                    <svg className="h-5 w-5 text-amber-400 dark:text-amber-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M8.257 3.099c.636-1.21 2.862-1.21 3.498 0l4.318 8.216a2.003 2.003 0 01-1.75 2.935H3.69a2.003 2.003 0 01-1.75-2.935l4.318-8.216zM9 11a1 1 0 112 0v1a1 1 0 11-2 0v-1zm1-4a1 1 0 00-1 1v2a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" />
                    </svg>
                </div>
                <div className="ml-3">
                    <h3 className="text-lg font-semibold text-amber-800 dark:text-amber-300">One-Time Database Setup</h3>
                    <div className="mt-2 text-sm text-amber-700 dark:text-amber-400">
                        <p>To enable customizable email templates, the 'email_templates' table needs to be created in your database. Please run the following SQL query once in your Supabase SQL Editor.</p>
                         <p className="mt-2">Navigate to your <a href="https://supabase.com/dashboard" target="_blank" rel="noopener noreferrer" className="font-bold underline">Supabase project</a> &rarr; SQL Editor &rarr; New query, and paste the code below.</p>
                    </div>
                    <div className="mt-4 relative bg-slate-800 dark:bg-black/50 p-4 rounded-md font-mono text-xs text-slate-200">
                        <button onClick={handleCopy} className="absolute top-2 right-2 bg-slate-600 hover:bg-slate-500 text-white px-2 py-1 rounded text-xs">{copied ? 'Copied!' : 'Copy'}</button>
                        <pre><code>{sql}</code></pre>
                    </div>
                </div>
            </div>
        </div>
    );
};

export const EmailTemplates: React.FC<{ session: Session, showNotification: (message: string, type: 'success' | 'error') => void; }> = ({ session, showNotification }) => {
    const { t } = useTheme();
    const [templates, setTemplates] = useState<EmailTemplate[]>([]);
    const [companySettings, setCompanySettings] = useState<Partial<CompanySettings>>({});
    const [companyLogo, setCompanyLogo] = useState<string | null>(null);
    const [editingTemplate, setEditingTemplate] = useState<{ key: string; data: Partial<EmailTemplate> } | null>(null);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [dbError, setDbError] = useState<string | null>(null);
    const userId = session.user.id;
    
    const previewHtml = useMemo(() => {
        if (!editingTemplate) return '';

        const dummyReplacements = {
            '{{booking_id}}': '123',
            '{{customer_name}}': 'John Doe',
            '{{pickup}}': '123 Main St, Anytown, USA',
            '{{dropoff}}': '456 Oak Ave, Otherville, USA',
            '{{datetime}}': new Date().toLocaleString(),
            '{{amount}}': '45.50',
            '{{company_name}}': companySettings.company_name || 'Your Company',
            '{{customer_contact}}': 'john.doe@example.com',
            '{{driver_name}}': 'Jane Smith',
            '{{payment_mode}}': 'Paid Online',
        };

        const replacePlaceholders = (template: string, replacements: Record<string, any>) => {
            let result = template;
            for (const key in replacements) {
                result = result.replace(new RegExp(`{{${key}}}`, 'g'), replacements[key] ?? '');
            }
            return result;
        };

        const createEmailTemplate = (content: string, companyName: string, companyLogoUrl: string | null): string => {
            const logoHtml = companyLogoUrl ? `<img src="${companyLogoUrl}" alt="${companyName} Logo" style="max-height: 70px; max-width: 200px;">` : `<h2>${companyName}</h2>`;
            return `
                <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
                    <div style="background-color: #f4f4f4; padding: 20px; text-align: center;">
                        ${logoHtml}
                    </div>
                    <div style="padding: 20px;">
                        ${content}
                    </div>
                    <div style="background-color: #f4f4f4; padding: 15px; text-align: center; font-size: 12px; color: #777;">
                        <p>${companyName} | This is an automated email. Please do not reply.</p>
                    </div>
                </div>
            `;
        };

        const body = replacePlaceholders(editingTemplate.data.body || '', dummyReplacements);
        const subject = replacePlaceholders(editingTemplate.data.subject || '', dummyReplacements);

        return `
            <html>
                <head><style>body { margin: 0; background-color: #f9fafb; }</style></head>
                <body>
                    <div style="background-color: #e5e7eb; padding: 1rem; font-family: sans-serif;">
                        <div style="background-color: white; padding: 0.5rem 1rem; border-radius: 0.5rem 0.5rem 0 0; border-bottom: 1px solid #d1d5db;">
                            <p style="font-size: 0.875rem; color: #4b5563;">Subject: <strong style="color: #111827;">${subject}</strong></p>
                        </div>
                    </div>
                    ${createEmailTemplate(body, companySettings.company_name || 'Your Company', companyLogo)}
                </body>
            </html>
        `;
    }, [editingTemplate, companySettings, companyLogo]);


    useEffect(() => {
        const checkAndFetchData = async () => {
            setLoading(true);
            setDbError(null);
            try {
                // Check if table exists
                const { data, error } = await supabase.from('email_templates').select('id').limit(1);
                if (error && error.message.includes('relation "public.email_templates" does not exist')) {
                    setDbError(createTableSql);
                    setLoading(false);
                    return;
                }
                
                // Fetch all data if table exists
                const [templatesRes, companyRes, formConfigRes] = await Promise.all([
                    supabase.from('email_templates').select('*').eq('uid', userId),
                    supabase.from('company_settings').select('company_name').eq('uid', userId).single(),
                    supabase.from('form_configurations').select('customizations').eq('uid', userId).single(),
                ]);

                if (templatesRes.error) throw templatesRes.error;
                setTemplates(templatesRes.data || []);
                
                if (companyRes.data) setCompanySettings(companyRes.data);
                if (formConfigRes.data) setCompanyLogo((formConfigRes.data.customizations as any)?.logo);

            } catch (err: any) {
                showNotification(`Error: ${err.message}`, 'error');
            } finally {
                setLoading(false);
            }
        };
        checkAndFetchData();
    }, [userId, showNotification]);

    const handleEdit = (templateKey: string) => {
        const existing = templates.find(t => t.template_name === templateKey);
        const defaultContent = DEFAULT_TEMPLATES[templateKey] || { subject: '', body: '' };
        setEditingTemplate({
            key: templateKey,
            data: existing || defaultContent
        });
        setIsModalOpen(true);
    };

    const handleSave = async () => {
        if (!editingTemplate || !userId) return;
        setSaving(true);
        const { key, data } = editingTemplate;
        const payload = {
            uid: userId,
            template_name: key,
            subject: data.subject || '',
            body: data.body || '',
            updated_at: new Date().toISOString()
        };
        const { error } = await supabase.from('email_templates').upsert(payload, { onConflict: 'uid, template_name' });

        if (error) {
            showNotification(`Save failed: ${error.message}`, 'error');
        } else {
            showNotification('Template saved successfully!', 'success');
            setTemplates(prev => {
                const index = prev.findIndex(t => t.template_name === key);
                if (index > -1) {
                    const newTemplates = [...prev];
                    newTemplates[index] = { ...prev[index], ...payload };
                    return newTemplates;
                }
                return [...prev, { id: Date.now(), ...payload }]; // Temp ID
            });
            setIsModalOpen(false);
        }
        setSaving(false);
    };

    if (loading) return null;

    return (
        <div className="max-w-5xl mx-auto space-y-8">
            <h1 className="text-3xl font-bold text-slate-800 dark:text-white">Email Templates</h1>
            
            {dbError ? (
                <SetupInstructions sql={dbError} />
            ) : (
                <>
                    <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-200/70 dark:border-slate-800/70">
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white">Branding</h2>
                        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Your company name and logo will appear in emails. You can edit them in Settings and the Form Builder.</p>
                        <div className="mt-4 flex items-center gap-6 p-4 bg-slate-50 dark:bg-slate-800/50 rounded-lg">
                            <div className="w-24 h-16 flex-shrink-0 bg-slate-200 dark:bg-slate-700 rounded-md flex items-center justify-center">
                                {companyLogo ? <img src={companyLogo} alt="Company Logo" className="max-h-full max-w-full object-contain"/> : <span className="text-xs text-slate-500">No Logo</span>}
                            </div>
                            <div>
                                <p className="text-sm text-slate-500">Company Name</p>
                                <p className="font-semibold text-slate-800 dark:text-white">{companySettings.company_name || 'Not Set'}</p>
                            </div>
                        </div>
                    </div>
                    
                    <div>
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white mb-4">Email Templates</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {Object.entries(EDITABLE_TEMPLATES).map(([key, templateInfo]) => (
                                <div key={key} className="bg-white dark:bg-slate-900 p-5 rounded-xl shadow-sm border border-slate-200/70 dark:border-slate-800/70 flex items-center justify-between gap-4">
                                    <div>
                                        <h3 className="font-semibold text-slate-800 dark:text-white">{templateInfo.name}</h3>
                                        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{templateInfo.description}</p>
                                    </div>
                                    <button onClick={() => handleEdit(key)} className="bg-primary-500 text-white font-semibold px-4 py-2 rounded-lg hover:bg-primary-600 transition-colors text-sm flex-shrink-0">
                                        Edit
                                    </button>
                                </div>
                            ))}
                        </div>
                    </div>
                </>
            )}

            {isModalOpen && editingTemplate && (
                <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={`Edit: ${EDITABLE_TEMPLATES[editingTemplate.key].name}`} size="5xl">
                     <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Subject</label>
                        <input 
                            type="text" 
                            value={editingTemplate.data.subject || ''} 
                            onChange={e => setEditingTemplate(p => p ? ({ ...p, data: { ...p.data, subject: e.target.value }}) : null)}
                            className="mt-1 block w-full border border-slate-300 dark:border-slate-600 rounded-md bg-white dark:bg-slate-700/50"
                        />
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                        <div>
                           <div>
                                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Body</label>
                                <textarea
                                    value={editingTemplate.data.body || ''}
                                    onChange={e => setEditingTemplate(p => p ? ({ ...p, data: { ...p.data, body: e.target.value }}) : null)}
                                    className="mt-1 block w-full h-[470px] p-4 font-sans text-sm resize-y bg-white dark:bg-slate-700/50 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                                    style={{ lineHeight: '1.6' }}
                                />
                            </div>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Live Preview</label>
                            <div className="mt-1 w-full h-[520px] border border-slate-300 dark:border-slate-600 rounded-md bg-white overflow-hidden">
                                <iframe
                                    srcDoc={previewHtml}
                                    className="w-full h-full border-0"
                                    title="Email Preview"
                                />
                            </div>
                        </div>
                    </div>
                    <div className="flex justify-end space-x-2 mt-6">
                        <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 bg-slate-200 text-slate-800 rounded-md hover:bg-slate-300 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600">Cancel</button>
                        <button type="button" onClick={handleSave} disabled={saving} className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 w-28 disabled:opacity-50">
                            {saving ? 'Saving...' : 'Save'}
                        </button>
                    </div>
                </Modal>
            )}
        </div>
    );
};
