

import React, { useState, useEffect } from 'react';
import { supabase } from '../services/supabase';
import type { Session } from '../types';
import type { Database } from '../services/database.types';
import { useTheme } from '../contexts/ThemeContext';
import { ICONS, PAYMENT_ICONS } from '../constants';
import { Tooltip } from './shared/Tooltip';

type IntegrationData = {
    stripe_public_key: string;
    stripe_secret_key: string;
    paypal_client_id: string;
    paypal_client_secret: string;
};

const SetupInstructions: React.FC<{ sql: string }> = ({ sql }) => {
    const [copied, setCopied] = useState(false);
    const handleCopy = () => {
        navigator.clipboard.writeText(sql).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className="bg-amber-50 dark:bg-amber-900/20 p-6 rounded-lg border-l-4 border-amber-400 dark:border-amber-500">
            <div className="flex">
                <div className="flex-shrink-0">
                    <svg className="h-5 w-5 text-amber-400 dark:text-amber-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M8.257 3.099c.636-1.21 2.862-1.21 3.498 0l4.318 8.216a2.003 2.003 0 01-1.75 2.935H3.69a2.003 2.003 0 01-1.75-2.935l4.318-8.216zM9 11a1 1 0 112 0v1a1 1 0 11-2 0v-1zm1-4a1 1 0 00-1 1v2a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" />
                    </svg>
                </div>
                <div className="ml-3">
                    <h3 className="text-lg font-semibold text-amber-800 dark:text-amber-300">Database Setup Required</h3>
                    <div className="mt-2 text-sm text-amber-700 dark:text-amber-400">
                        <p>The 'payment_integrations' table is missing from your database. To enable this feature, please run the following SQL query in your Supabase SQL Editor.</p>
                        <p className="mt-2">Navigate to <a href="https://supabase.com/dashboard" target="_blank" rel="noopener noreferrer" className="font-bold underline">your Supabase project</a> &rarr; SQL Editor &rarr; New query, and paste the code below.</p>
                    </div>
                    <div className="mt-4 relative bg-slate-800 dark:bg-black/50 p-4 rounded-md font-mono text-xs text-slate-200">
                        <button onClick={handleCopy} className="absolute top-2 right-2 bg-slate-600 hover:bg-slate-500 text-white px-2 py-1 rounded text-xs">{copied ? 'Copied!' : 'Copy'}</button>
                        <pre><code>{sql}</code></pre>
                    </div>
                </div>
            </div>
        </div>
    );
};


export const Integrations: React.FC<{ session: Session; showNotification: (message: string, type: 'success' | 'error') => void; }> = ({ session, showNotification }) => {
    const { t } = useTheme();
    const [integrations, setIntegrations] = useState<IntegrationData>({
        stripe_public_key: '',
        stripe_secret_key: '',
        paypal_client_id: '',
        paypal_client_secret: '',
    });
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [dbError, setDbError] = useState<string | null>(null);
    const [showStripeSecret, setShowStripeSecret] = useState(false);
    const [showPaypalSecret, setShowPaypalSecret] = useState(false);
    const userId = session.user.id;

    useEffect(() => {
        const fetchIntegrations = async () => {
            setLoading(true);
            setDbError(null);
            const { data, error } = await supabase
                .from('payment_integrations')
                .select('*')
                .eq('uid', userId)
                .maybeSingle();

            if (error) {
                if (error.message.includes('relation "public.payment_integrations" does not exist')) {
                    const createTableSql = `CREATE TABLE public.payment_integrations (\n  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n  uid uuid NOT NULL,\n  created_at timestamp with time zone NOT NULL DEFAULT now(),\n  stripe_public_key text NULL,\n  stripe_secret_key text NULL,\n  paypal_client_id text NULL,\n  paypal_client_secret text NULL,\n  CONSTRAINT payment_integrations_pkey PRIMARY KEY (id),\n  CONSTRAINT payment_integrations_uid_key UNIQUE (uid),\n  CONSTRAINT payment_integrations_uid_fkey FOREIGN KEY (uid) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE\n);\n\nALTER TABLE public.payment_integrations ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY "Enable read access for authenticated users" ON public.payment_integrations FOR SELECT USING (auth.uid() = uid);\nCREATE POLICY "Enable insert for authenticated users" ON public.payment_integrations FOR INSERT WITH CHECK (auth.uid() = uid);\nCREATE POLICY "Enable update for authenticated users" ON public.payment_integrations FOR UPDATE USING (auth.uid() = uid);`;
                    setDbError(createTableSql);
                } else {
                    showNotification(`Error fetching integrations: ${error.message}`, 'error');
                }
            } else if (data) {
                setIntegrations({
                    stripe_public_key: data.stripe_public_key || '',
                    stripe_secret_key: data.stripe_secret_key || '',
                    paypal_client_id: data.paypal_client_id || '',
                    paypal_client_secret: data.paypal_client_secret || '',
                });
            }
            setLoading(false);
        };

        fetchIntegrations();
    }, [userId, showNotification]);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setIntegrations(prev => ({ ...prev, [name]: value }));
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        setSaving(true);
        
        const payload: Database['public']['Tables']['payment_integrations']['Insert'] = {
            uid: userId,
            ...integrations
        };

        const { error } = await supabase
            .from('payment_integrations')
            .upsert([payload], { onConflict: 'uid' });

        if (error) {
            showNotification(`Error saving integrations: ${error.message}`, 'error');
        } else {
            showNotification('Integration settings saved successfully!', 'success');
        }
        setSaving(false);
    };
    
    const inputClasses = "mt-1 block w-full px-4 py-2.5 border border-slate-300/70 dark:border-slate-700/70 rounded-lg placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white dark:focus:ring-offset-slate-900 focus:ring-primary-500 sm:text-sm bg-white dark:bg-slate-800/70 text-slate-900 dark:text-white transition";
    const labelClasses = "block text-sm font-medium text-slate-700 dark:text-slate-300";

    if (loading) {
        return (
            <div className="animate-pulse">
                <div className="h-8 bg-slate-200 dark:bg-slate-700 rounded w-1/4 mb-6"></div>
                <div className="bg-white dark:bg-slate-800 p-6 rounded-[20px] max-w-3xl mx-auto space-y-6">
                    <div className="h-6 bg-slate-200 dark:bg-slate-700 rounded w-1/3 mb-4"></div>
                    <div className="h-10 bg-slate-200 dark:bg-slate-700 rounded-lg w-full"></div>
                    <div className="h-10 bg-slate-200 dark:bg-slate-700 rounded-lg w-full"></div>
                    <div className="h-6 bg-slate-200 dark:bg-slate-700 rounded w-1/3 mb-4 mt-6"></div>
                    <div className="h-10 bg-slate-200 dark:bg-slate-700 rounded-lg w-full"></div>
                    <div className="h-10 bg-slate-200 dark:bg-slate-700 rounded-lg w-full"></div>
                    <div className="flex justify-end pt-5">
                         <div className="h-10 bg-slate-300 dark:bg-slate-600 rounded-lg w-32"></div>
                    </div>
                </div>
            </div>
        );
    }
    
    if (dbError) {
        return (
            <div>
                 <h1 className="text-2xl font-bold text-slate-800 dark:text-white mb-6">Payment Integrations</h1>
                 <div className="max-w-3xl mx-auto">
                    <SetupInstructions sql={dbError} />
                 </div>
            </div>
        )
    }

    return (
        <div>
            <h1 className="text-2xl font-bold text-slate-800 dark:text-white mb-6">Payment Integrations</h1>
            <form onSubmit={handleSave} className="bg-white dark:bg-slate-800 p-6 rounded-[20px] max-w-3xl mx-auto space-y-8">
                {/* Stripe Section */}
                <div>
                    <h2 className="text-lg font-semibold flex items-center gap-3 text-slate-800 dark:text-white border-b border-slate-200 dark:border-slate-700 pb-3 mb-4">
                        <svg viewBox="0 0 24 24" className="w-8 h-8" dangerouslySetInnerHTML={{ __html: PAYMENT_ICONS.find(p => p.name === 'stripe')?.icon || '' }} />
                        Stripe Configuration
                    </h2>
                    <div className="space-y-4">
                        <div>
                            <label htmlFor="stripe_public_key" className={labelClasses}>Publishable Key</label>
                            <input id="stripe_public_key" name="stripe_public_key" type="text" value={integrations.stripe_public_key} onChange={handleInputChange} className={inputClasses} placeholder="pk_live_..."/>
                        </div>
                        <div>
                            <label htmlFor="stripe_secret_key" className={labelClasses}>Secret Key</label>
                             <div className="relative">
                                <input id="stripe_secret_key" name="stripe_secret_key" type={showStripeSecret ? 'text' : 'password'} value={integrations.stripe_secret_key} onChange={handleInputChange} className={`${inputClasses} pr-10`} placeholder="sk_live_..."/>
                                <Tooltip content={showStripeSecret ? 'Hide key' : 'Show key'}>
                                    <button type="button" onClick={() => setShowStripeSecret(!showStripeSecret)} className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">
                                        <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">{showStripeSecret ? ICONS.HidePassword : ICONS.ShowPassword}</svg>
                                    </button>
                                </Tooltip>
                            </div>
                        </div>
                    </div>
                </div>
                
                {/* PayPal Section */}
                <div>
                    <h2 className="text-lg font-semibold flex items-center gap-3 text-slate-800 dark:text-white border-b border-slate-200 dark:border-slate-700 pb-3 mb-4">
                        <svg viewBox="0 0 24 24" className="w-8 h-8" dangerouslySetInnerHTML={{ __html: PAYMENT_ICONS.find(p => p.name === 'paypal')?.icon || '' }} />
                        PayPal Configuration
                    </h2>
                     <div className="space-y-4">
                        <div>
                            <label htmlFor="paypal_client_id" className={labelClasses}>Client ID</label>
                            <input id="paypal_client_id" name="paypal_client_id" type="text" value={integrations.paypal_client_id} onChange={handleInputChange} className={inputClasses} placeholder="Your PayPal Client ID"/>
                        </div>
                        <div>
                            <label htmlFor="paypal_client_secret" className={labelClasses}>Client Secret</label>
                             <div className="relative">
                                <input id="paypal_client_secret" name="paypal_client_secret" type={showPaypalSecret ? 'text' : 'password'} value={integrations.paypal_client_secret} onChange={handleInputChange} className={`${inputClasses} pr-10`} placeholder="Your PayPal Client Secret"/>
                                <Tooltip content={showPaypalSecret ? 'Hide key' : 'Show key'}>
                                    <button type="button" onClick={() => setShowPaypalSecret(!showPaypalSecret)} className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">
                                        <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">{showPaypalSecret ? ICONS.HidePassword : ICONS.ShowPassword}</svg>
                                    </button>
                                </Tooltip>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="pt-5 border-t border-slate-200 dark:border-slate-700">
                    <div className="flex justify-end">
                        <button type="submit" disabled={saving} className="inline-flex justify-center items-center py-2.5 px-5 border border-transparent text-sm font-medium rounded-lg text-white bg-primary-600 hover:bg-primary-700 disabled:opacity-50">
                            {saving ? (
                                <>
                                    <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                                    {t('saving', 'Saving...')}
                                </>
                            ) : t('save_integrations', 'Save Integrations')}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    );
};